name: golangci-lint
on: [push, pull_request]
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.30

          # Optional: golangci-lint command line arguments.
          args: --issues-exit-code=0 --exclude-use-default --enable-all -D asciicheck -D depguard -D dogsled -D funlen -D gci -D gochecknoglobals -D gochecknoinits -D gocognit -D gocyclo -D godot -D godox -D goheader -D gomodguard -D nlreturn -D noctx -D bodyclose -D rowserrcheck -D sqlclosecheck -D stylecheck -D testpackage -D wsl

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: true
